format = """
$os\
$directory\
$docker_context\
$git_branch\
$git_status\
$git_commit\
$nodejs\
$rust\
$golang\
$php\
$python\
$fill\
$time\
$line_break\
$character"""

add_newline = true

[directory]
format = "[ $path ]($style)"
truncation_length=8
truncate_to_repo=false
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[line_break]
disabled = false

[fill]
symbol = ' '

[git_branch]
format = "$branch $symbol "
symbol = " "

[git_status]
format="$all_status$ahead_behind  "
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = " ${count}"

[git_commit]
format = "\\($hash\\) \\($tag\\)"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
format = '\($state( $progress_current/$progress_total)) '

[nodejs]
symbol = " "
format = ' $symbol ($version) '

[rust]
symbol = "󱘗 "
format = ' $symbol ($version) '

[golang]
symbol = " "
format = ' $symbol ($version) '

[php]
symbol = " "
format = ' $symbol ($version) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '  $time '

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "
format = ' $symbol $environment'

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "


[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[ocaml]
symbol = " "

[os]
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "


[pijul_channel]
symbol = " "

[python]
symbol = " "
format = '${symbol} (${version} )(\($virtualenv\) )'
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3"]
version_format = "v${raw}"

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "


[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
