import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]
live_config_reload = true
window.opacity = 0.8
window.decorations = "none"
[window.padding]
x = 15
y = 15

[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black='#555555'
blue='#bd93f9'
cyan='#8be9fd'
green='#50fa7b'
magenta='#ff79c6'
red='#ff5555'
white='#ffffff'
yellow='#f1fa8c'

[colors.cursor]
cursor = "#bbbbbb"
text = "#ffffff"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#44475a"
text = "#ffffff"

[font]
size = 14

[font.bold]
family = "HackNerdFont"
style = "Bold"

[font.normal]
family = "HackNerdFont"
style = "Regular"

[shell]
program = "/usr/bin/zsh"
